# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Feirbrais\Desktop\Diplom\gui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import  QStandardItemModel,QStandardItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(2000, 2000))
        MainWindow.setStyleSheet("QWidget {\n"
"    border: opx;\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QGroupBox#MenuGroupBox QPushButton:hover {\n"
"    background-color: rgb(212, 212, 212);\n"
"}\n"
"QGroupBox#MenuGroupBox QPushButton:focus {\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"\n"
"QGroupBox#ProfileGroupBox QLineEdit {\n"
"    border: 1px solid gray;\n"
"}\n"
"QGroupBox#ProfileGroupBox QLabel#PhotoIcon {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton#exitButton:hover {\n"
"    background-color: rgb(255, 81, 46);\n"
"}\n"
"QPushButton#scrollDownButton:hover {\n"
"    background-color: rgb(174, 255, 250);\n"
"}\n"
"QTableView {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QGroupBox#ProfilesControlGroupBox QPushButton:hover{\n"
"    background-color: rgb(212, 212, 212);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.titleGroupBox.setMinimumSize(QtCore.QSize(700, 36))
        self.titleGroupBox.setMaximumSize(QtCore.QSize(700, 36))
        self.titleGroupBox.setTitle("")
        self.titleGroupBox.setObjectName("titleGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleGroupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IconLabel = QtWidgets.QLabel(self.titleGroupBox)
        self.IconLabel.setMinimumSize(QtCore.QSize(36, 36))
        self.IconLabel.setMaximumSize(QtCore.QSize(36, 36))
        self.IconLabel.setText("")
        self.IconLabel.setPixmap(QtGui.QPixmap("C:\\Users\\Feirbrais\\Desktop\\Diplom\\gui\\imgs/titleIcon.png"))
        self.IconLabel.setObjectName("IconLabel")
        self.horizontalLayout.addWidget(self.IconLabel)
        self.NameLabel = QtWidgets.QLabel(self.titleGroupBox)
        self.NameLabel.setObjectName("NameLabel")
        self.horizontalLayout.addWidget(self.NameLabel)
        self.scrollDownButton = QtWidgets.QPushButton(self.titleGroupBox)
        self.scrollDownButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.scrollDownButton.setFont(font)
        self.scrollDownButton.setObjectName("scrollDownButton")
        self.horizontalLayout.addWidget(self.scrollDownButton)
        self.exitButton = QtWidgets.QPushButton(self.titleGroupBox)
        self.exitButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.verticalLayout.addWidget(self.titleGroupBox)
        self.MainGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.MainGroupBox.setMinimumSize(QtCore.QSize(639, 341))
        self.MainGroupBox.setTitle("")
        self.MainGroupBox.setObjectName("MainGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.MainGroupBox)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MenuGroupBox = QtWidgets.QGroupBox(self.MainGroupBox)
        self.MenuGroupBox.setMinimumSize(QtCore.QSize(160, 0))
        self.MenuGroupBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.MenuGroupBox.setTitle("")
        self.MenuGroupBox.setObjectName("MenuGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MenuGroupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ProfileOpenButton = QtWidgets.QPushButton(self.MenuGroupBox)
        self.ProfileOpenButton.setMinimumSize(QtCore.QSize(0, 30))
        self.ProfileOpenButton.setObjectName("ProfileOpenButton")
        self.verticalLayout_2.addWidget(self.ProfileOpenButton)
        self.ProfileredactorOpenButton = QtWidgets.QPushButton(self.MenuGroupBox)
        self.ProfileredactorOpenButton.setMinimumSize(QtCore.QSize(0, 30))
        self.ProfileredactorOpenButton.setMaximumSize(QtCore.QSize(160, 16777215))
        self.ProfileredactorOpenButton.setObjectName("ProfileredactorOpenButton")
        self.verticalLayout_2.addWidget(self.ProfileredactorOpenButton)
        self.VoidGroupBox = QtWidgets.QGroupBox(self.MenuGroupBox)
        self.VoidGroupBox.setTitle("")
        self.VoidGroupBox.setObjectName("VoidGroupBox")
        self.verticalLayout_2.addWidget(self.VoidGroupBox)
        self.ExitProfileButton = QtWidgets.QPushButton(self.MenuGroupBox)
        self.ExitProfileButton.setMinimumSize(QtCore.QSize(0, 30))
        self.ExitProfileButton.setObjectName("ExitProfileButton")
        self.verticalLayout_2.addWidget(self.ExitProfileButton)
        self.horizontalLayout_2.addWidget(self.MenuGroupBox)

        #Left groupBox in main groupBox
        self.ProfileGroupBox = QtWidgets.QGroupBox(self.MainGroupBox)
        self.ProfileGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfileGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ProfileGroupBox.setTitle("")
        self.ProfileGroupBox.setObjectName("ProfileGroupBox")

        #User group box
        self.UserGroupBox = QtWidgets.QGroupBox(self.ProfileGroupBox)
        self.UserGroupBox.setGeometry(QtCore.QRect(0, 0, 540, 364))
        self.UserGroupBox.setTitle("")
        self.UserGroupBox.setObjectName("UserGroupBox")
        self.PhotoIcon = QtWidgets.QLabel(self.UserGroupBox)
        self.PhotoIcon.setGeometry(QtCore.QRect(10, 10, 100, 100))
        self.PhotoIcon.setMinimumSize(QtCore.QSize(100, 100))
        self.PhotoIcon.setText("")
        self.PhotoIcon.setPixmap(QtGui.QPixmap("C:\\Users\\Feirbrais\\Desktop\\Diplom\\gui\\imgs/avatar-base.jpg"))
        self.PhotoIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.PhotoIcon.setObjectName("PhotoIcon")
        self.StatusLabelText = QtWidgets.QLabel(self.UserGroupBox)
        self.StatusLabelText.setGeometry(QtCore.QRect(120, 10, 50, 20))
        self.StatusLabelText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StatusLabelText.setObjectName("StatusLabelText")
        self.LoginLabel = QtWidgets.QLabel(self.UserGroupBox)
        self.LoginLabel.setGeometry(QtCore.QRect(120, 35, 50, 20))
        self.LoginLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LoginLabel.setObjectName("LoginLabel")
        self.PasswordLabelText = QtWidgets.QLabel(self.UserGroupBox)
        self.PasswordLabelText.setGeometry(QtCore.QRect(120, 60, 50, 20))
        self.PasswordLabelText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PasswordLabelText.setObjectName("PasswordLabelText")
        self.StatusLabel = QtWidgets.QLabel(self.UserGroupBox)
        self.StatusLabel.setGeometry(QtCore.QRect(180, 10, 120, 20))
        self.StatusLabel.setObjectName("StatusLabel")
        self.lineEdit = QtWidgets.QLineEdit(self.UserGroupBox)
        self.lineEdit.setGeometry(QtCore.QRect(180, 35, 250, 20))
        self.lineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.UserGroupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 60, 250, 20))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.LoginRedactorButton = QtWidgets.QPushButton(self.UserGroupBox)
        self.LoginRedactorButton.setGeometry(QtCore.QRect(435, 35, 20, 20))
        self.LoginRedactorButton.setMinimumSize(QtCore.QSize(20, 20))
        self.LoginRedactorButton.setMaximumSize(QtCore.QSize(20, 20))
        self.LoginRedactorButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Feirbrais\\Desktop\\Diplom\\gui\\imgs/redactoricon_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LoginRedactorButton.setIcon(icon)
        self.LoginRedactorButton.setObjectName("LoginRedactorButton")
        self.PasswordRedactorButton = QtWidgets.QPushButton(self.UserGroupBox)
        self.PasswordRedactorButton.setGeometry(QtCore.QRect(435, 60, 20, 20))
        self.PasswordRedactorButton.setMinimumSize(QtCore.QSize(20, 20))
        self.PasswordRedactorButton.setMaximumSize(QtCore.QSize(20, 20))
        self.PasswordRedactorButton.setText("")
        self.PasswordRedactorButton.setIcon(icon)
        self.PasswordRedactorButton.setObjectName("PasswordRedactorButton")
        self.SaveNewLoginButton = QtWidgets.QPushButton(self.UserGroupBox)
        self.SaveNewLoginButton.setGeometry(QtCore.QRect(460, 35, 20, 20))
        self.SaveNewLoginButton.setMinimumSize(QtCore.QSize(20, 20))
        self.SaveNewLoginButton.setMaximumSize(QtCore.QSize(20, 20))
        self.SaveNewLoginButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Feirbrais\\Desktop\\Diplom\\gui\\imgs/saveicon_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveNewLoginButton.setIcon(icon1)
        self.SaveNewLoginButton.setObjectName("SaveNewLoginButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.UserGroupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 85, 20, 20))
        self.pushButton_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Feirbrais\\Desktop\\Diplom\\gui\\imgs/watch_pass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.UserGroupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 60, 20, 20))
        self.pushButton_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.ProfileGroupBox)
        self.verticalLayout.addWidget(self.MainGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        #Users datas
        self.ProfilesControlGroupBox = QtWidgets.QGroupBox(self.ProfileGroupBox)
        self.ProfilesControlGroupBox.setGeometry(QtCore.QRect(0, 0, 540, 364))
        self.ProfilesControlGroupBox.setTitle("")
        self.ProfilesControlGroupBox.setObjectName("ProfilesControlGroupBox")
        self.usersTableView = QtWidgets.QTableView(self.ProfilesControlGroupBox)
        self.usersTableView.setGeometry(QtCore.QRect(10, 10, 300, 350))
        self.usersTableView.setObjectName("usersTableView")
        self.usersTableView.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.ProfilesControlGroupBox)
        self.verticalLayout.addWidget(self.MainGroupBox)
        #buttons
        self.RedactPassForUser = QtWidgets.QPushButton(self.ProfilesControlGroupBox)
        self.RedactPassForUser.setGeometry(QtCore.QRect(310, 10, 170, 30))
        self.RedactPassForUser.setObjectName("RedactPassForUser")
        self.RedactStatusForUserButton = QtWidgets.QPushButton(self.ProfilesControlGroupBox)
        self.RedactStatusForUserButton.setGeometry(QtCore.QRect(310, 50, 170, 30))
        self.RedactStatusForUserButton.setObjectName("RedactStatusForUserButton")
        self.RedactLoginForUserButton = QtWidgets.QPushButton(self.ProfilesControlGroupBox)
        self.RedactLoginForUserButton.setGeometry(QtCore.QRect(310, 90, 170, 23))
        self.RedactLoginForUserButton.setObjectName("RedactLoginForUserButton")
        self.AddNewUserButton = QtWidgets.QPushButton(self.ProfilesControlGroupBox)
        self.AddNewUserButton.setGeometry(QtCore.QRect(310, 300, 170, 30))
        self.AddNewUserButton.setObjectName("AddNewUserButton")
        self.DeleteUserButton = QtWidgets.QPushButton(self.ProfilesControlGroupBox)
        self.DeleteUserButton.setGeometry(QtCore.QRect(310, 330, 170, 30))
        self.DeleteUserButton.setObjectName("DeleteUserButton")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NameLabel.setText(_translate("MainWindow", "NetInspector"))
        self.scrollDownButton.setText(_translate("MainWindow", "—"))
        self.exitButton.setText(_translate("MainWindow", "×"))
        self.ProfileOpenButton.setText(_translate("MainWindow", "Профиль"))
        self.ProfileredactorOpenButton.setText(_translate("MainWindow", "Управление пользователями"))
        self.ExitProfileButton.setText(_translate("MainWindow", "Выход"))
        self.StatusLabelText.setText(_translate("MainWindow", "Статус:"))
        self.LoginLabel.setText(_translate("MainWindow", "Логин:"))
        self.PasswordLabelText.setText(_translate("MainWindow", "Пароль:"))
        self.StatusLabel.setText(_translate("MainWindow", "Админ"))
        self.RedactPassForUser.setText(_translate("MainWindow", "Изменить пароль пользователя"))
        self.RedactStatusForUserButton.setText(_translate("MainWindow", "Изменить статус пользователя"))
        self.RedactLoginForUserButton.setText(_translate("MainWindow", "Изменить логин пользователя"))
        self.AddNewUserButton.setText(_translate("MainWindow", "Добавить пользователя"))
        self.DeleteUserButton.setText(_translate("MainWindow", "Удалить пользователя"))
